### ISSUE TITLE
Function WithHosts commented

### ISSUE THREAD

**Issue by nchiaro** [elastic/go-elasticsearch#10]
I downloaded the code to perform tests and added the code that is in the README.

The following error appears:

undefined: client.WithHosts
cannot use body (type map[string]interface {}) as type api.SearchOption in argument to c.API.Search

I open the code in options.go in the client folder and I see that it is commented.

Can you put an example that works in the README? Or tell me where I can find how to run it. 

Thank you.

Regards,
Natalia.

**Comment by 7AC** [comment]
As stated in the README this is still work in progress. You can track the items that are still pending via https://github.com/elastic/go-elasticsearch/issues/5.

**Comment by zhaojiexi** [comment]
I have the same problem.

**Comment by duck-of-death** [comment]
I was having the same issue, it looks like the function in go-elasticsearch/client/option.go is WithHost() not WithHost**s**()

The function WithHost() takes a string parameter however, so WithHost("http://localhost:9200") instead of WithHosts([]string{"https://elasticsearch:9200"}).

It looks like there is a better client inside of the libbeats library, hopefully it will be reincorporated into this repo.

**Comment by karmi** [comment]
Hello, the project has been replaced today with a new codebase, and the initializer works differently now: https://github.com/elastic/go-elasticsearch#usage

Is it OK if I close this issue?
