### ISSUE TITLE
Ignore ELASTICSEARCH_URL when config set?

### ISSUE THREAD

**Issue by graphaelli** [elastic/go-elasticsearch#113]
Per https://github.com/elastic/go-elasticsearch/blob/cb4ea94ef05b5d9a9c737619e2c1e99f7430aa8b/elasticsearch.go#L86-L100, library users are not permitted to set both `ELASTICSEARCH_URL` in the environment and pass in addresses - I'd like to reconsider this limitation, perhaps some background on why would help?  I don't see the same restriction in the python client.

APM Server recently started using go-elasticsearch and coincidentally someone introduced `ELASTICSEARCH_URL` into the test environment, causing tests fail as the es client could not be created.  This was surprising since APM Server always creates a client with `config.Addresses`.

**Comment by karmi** [comment]
I think the motivation was to prevent surprises about what happens when both are set: does one take precedence over the other? Do they get merged? (Eg., in your case, if the environment variable gets set suddenly in a test environment, should it be picked up by the client?)

I'm fine with removing the restriction, but we need to figure out a clear solution to the case when both are set. Intuitively, I'd say that when `config.Addresses` are set, the environment variable would be ignored.

**Comment by graphaelli** [comment]
Agreed, I'd expect code to take precedence over environment variables.

**Comment by karmi** [comment]
I've merged the 86a626c2 commit into `master`, `6.x` and `7.x` branches. It will be part of the next release.
