### ISSUE TITLE
Missing documentation: available APIs and how to (easily) call them outside of large example code

### ISSUE THREAD

**Issue by nmiodice** [elastic/go-elasticsearch#119]
The onboarding for using this client is a little rough and required extensive searching through the code and a lot of trial and error. I think that it would help to have some documentation for how to actually call the APIs in very simple terms. They can be called in many ways and its not clear what the intended usage is.

**Comment by karmi** [comment]
I must say I'm quite surprised by your statement here.

The package mirrors the Elasticsearch APIs 1:1, so if you look up eg. the documentation for [indexing data](https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started-index.html#getting-started-index) in the official documentation, the corresponding Go is quite straightforward. In fact, in the `master` version of the documentation, you can choose between examples for _Console_ and for various programming languages, including Go.

Also, the package comes with a lot of examples in the `_examples` folder, demonstrating use cases ranging from simple usage to client configuration/customization, deserializing responses, and so on. Even the [main example](https://github.com/elastic/go-elasticsearch/blob/master/_examples/main.go), which is included in the README, arguable demonstrates a lot of techniques for using the client.

> I think that it would help to have some documentation for how to actually call the APIs in very simple terms.

I'm not sure about that, to be honest. If you look up eg. the "Index" API, either on [pkg.go.dev](https://pkg.go.dev/github.com/elastic/go-elasticsearch/v7@v7.5.0/esapi?tab=doc#Index), or locally, it already tells you how to use that particular API:

    go doc esapi.Index
    (...)
    type Index func(index string, body io.Reader, o ...func(*IndexRequest)) (*Response, error)
    Index creates or updates a document in an index.

    (...)
    func (f Index) WithDocumentID(v string) func(*IndexRequest)
    (...)

Adding a "simple" example for each API wouldn't perhaps bring much value, since it would only demonstrate that you pass an index name as a `string` and the document as an `io.Reader` — which the documentation (or IDE integration) already tells you.

That's why I have worked on a comprehensive examples in the `_examples` folder, instead.

> They can be called in many ways and its not clear what the intended usage is.

I'm curious what you mean by this, specifically. The only thing which comes to mind is that the `esapi` package exports two types for each API, as it states in the documentation:

    For each Elasticsearch API, such as "Index", the package exports two
    corresponding types: a function and a struct.

    The function type allows you to call the Elasticsearch API as a method on
    the client, passing the parameters as arguments:
    (...)
    The struct type allows for a more hands-on approach, where you create a new
    struct, with the request configuration as fields, and call the Do() method
    with a context and the client as arguments:
    (...)

That's really all there is — the function type is a higher-level wrapper around the struct type, with a more fluent interface. Some people prefer the former, some the latter.

Again, I'm curious to hear more details.

**Comment by nmiodice** [comment]
Hi @karmi ,

Sorry to have missed [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started-index.html#getting-started-index) as it has a lot of what I was hoping to see. This is exactly the pattern that I was hoping to see.

I think this can be closed due to me being a moron :) 

Sorry for the churn!

Nick

**Comment by karmi** [comment]
No worries at all! It actually made me think that linking to the "Getting Started" documentation at elastic.co is worth adding to the README — I've always operated with the assumption that the package users are already familiar with the ES APIs, but the link will be helpful.

**Comment by surlyengineer** [comment]
FWIW I'd tend to agree it's a little intimidating/inaccessible at first read, I'm familiar with the ES API but pretty new to Go, and as compared to [the python library examples](https://elasticsearch-py.readthedocs.io/en/master/) or [the java docs](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-index.html) I had a hard time parsing what's up. 

The paragraph you cited about the two ways to call it is indeed very helpful, as is [this godoc](https://godoc.org/github.com/elastic/go-elasticsearch/esapi), for whatever reason it took me a long time to find that page and the godocs I got dropped into at first were more about the client and had dead links for the examples.

Which is maybe a long way to say I'm not sure there needs to be new content, so much as maybe a re-shuffling of the readme to put some of the simpler usage and configuration more prominently up at the top.  Would be happy to take a crack at it if I can find a few minutes if it'd be helpful.

**Comment by karmi** [comment]
Hello, @surlyengineer! I'm quite surprised — again :) — that the examples are lacking, especially in comparison with the Python client, which has considerably less actual (runnable) examples than Go.

Would you be so kind to describe in more detail:

* In what way the Python client main example is more helpful than the Go [one](https://github.com/elastic/go-elasticsearch/blob/master/_examples/main.go)?

* What were the problems you needed to solve, and didn't find a good way in the Go docs, ie. something like "I wanted to do X with Elasticsearch and couldn't find the doc/example/etc"

Thanks!
