### ISSUE TITLE
Strongly typed API responses would be *super* helpful

### ISSUE THREAD

**Issue by nmiodice** [elastic/go-elasticsearch#120]
APIs with strongly typed returns are a little painful to work with because the response is essentially a byte array. Examples are health check API and cluster info API. I'm sure there are more -- I'm just diving into these APIs.

It would be really helpful if the API took care of deserializing these types into a struct with the proper types, so that every client of the API need not repeat and redefine these types.

**Comment by karmi** [comment]
> APIs with strongly typed returns are a little painful to work with (...)

I'm a little bit confused by this part, but it seems like the overall concern is that the client returns the Elasticsearch response as an `io.Reader` — is that correct?

If so, this is intentional, for two reasons. The first reason is that this is a low-level client, which doesn't deserialiaze responses — and doesn't serialize requests, either —, in the interest of efficiency and performance. That's a job for a higher-level library.

The second reason is pragmatic. The client closely follows the REST API specification for Elasticsearch — see eg. the [Count API](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/count.json). Every API implementation in the `esapi` package is generated from the specification, in fact. That's why this package can support Elasticsearch 5.x, 6.x, 7.x and 8.x, and _guarantee_ the compatibility — there is no manual work involved. That's also why this package can be released on the same day as the Elastic Stack.

There is no specification like that for the REST API _payloads_, yet. We are discussing the best approaches for this for some time, but as the Elasticsearch APIs are quite variable in what they receive and return, it's not a trivial problem to solve. But in any case, until there's a specification to base the code on, it is not feasible to provide a typed response such as `esapi.CountResponse`, as that would require capturing this information manually.

I've replied in detail, since this issue comes up from time to time, especially in comparison with the `olivere/elastic` package, so I can refer later questions to this issue.

**Comment by nmiodice** [comment]
> I'm a little bit confused by this part, but it seems like the overall concern is that the client returns the Elasticsearch response as an io.Reader — is that correct?

Yes.

I cannot say that I'm an expert on the ES APIs as I'm relatively new to the technology, but I think that this is somewhat of a barrier for adoption to clients like this one.

I understand the point you are making in regards to the lack of strongly typed API response from the underlying ES services. In that case I agree that there is not a ton that you can do. However, once that is available (which I assume is not something that you have direct control over) it would be fantastic to provide typed response payloads.

A good example is the [Azure DevOps Go SDK](https://github.com/microsoft/azure-devops-go-api), which is generated from (i think) swagger documents similar to what you linked to. 

Is there an open issue that I can follow with regards to adding typing annotations for the API responses?

**Comment by karmi** [comment]
You're absolutely right that the lack of a convenient types for responses is a barrier — it's always preferable to write something like `res.Hits.Hits[0].Source["foo"]` then having to deal with parsing and such. But then again, yes, a complete specification for Elasticsearch responses is not something under my control, and therefore I have no foundation to generate these types reliably.

However, look eg. at the https://github.com/elastic/go-elasticsearch/blob/master/_examples/encoding/gjson.go example — in many cases, people just want to "pluck" couple of values from the response, and the `tidwall/gjson` package is _very_ convenient for that.

There's not a single issue in the Elasticsearch repo related to the request/response body specification, I think. There's general agreement that this is something we need, but no timeline for that yet...

**Comment by nmiodice** [comment]
This is a pretty cool package, thanks for sharing.

I suppose that there is no reason for this to be open based on the information you have provided, so feel free to close it. 

Happy Holidays (should you be celebrating any)!

**Comment by karmi** [comment]
Hello @nmiodice , sorry for a delayed response and a happy new year!!

I think I'll probably create a new issue about the topic, summarizing all the aspects, and pin it to the repository, so it's easier for people to find, and participate in the discussion... It's an important thing to address, since people do keep asking, in this repository, and in `olivere/elastic` as well.
