### ISSUE TITLE
Improving semantics

### ISSUE THREAD

**Issue by owlwalks** [elastic/go-elasticsearch#128]
To form a query at the moment:

```
 var buf bytes.Buffer
  query := map[string]interface{}{
    "query": map[string]interface{}{
      "match": map[string]interface{}{
        "title": "test",
      },
    },
  }
  if err := json.NewEncoder(&buf).Encode(query); err != nil {
    log.Fatalf("Error encoding query: %s", err)
  }
```
Would love to see the library can abstract away those `map[string]interface{}` frictions:

Something like this maybe:
```
req := es.NewSearchRequest()
req.Match("title", "test")
req.Size(20)
...
```

**Comment by aladine** [comment]
I am also looking forwards to this new query builder that can add boolean, terms, match queries... The hard thing is the number of nested levels may be large.

**Comment by karmi** [comment]
Hello, this question pops up quite often, not only for the Query DSL, but also eg. for the responses (see https://github.com/elastic/go-elasticsearch/issues/120). As I've explained in those issues, at the moment it's not feasible to provide any high-level API like this, because there's no formal specification to base the code generation on. (The whole API is generated from the [REST API specification](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec), but that includes only the API "surface", ie. endpoints, HTTP methods, parameters, not the request or response bodies.)

There are number of examples how to deal with the search results or the Query DSL in the `_examples` folder, see eg. https://github.com/elastic/go-elasticsearch/blob/ca32bbd4b9860afbb832ebbaa9149a50740e9f9a/_examples/xkcdsearch/store.go#L196.

I'm afraid there's no immediate solution to what you're after at the moment.
