### ISSUE TITLE
Security Issue with %q?

### ISSUE THREAD

**Issue by moon-bits** [elastic/go-elasticsearch#152]
Hi,

looking at one of the examples ([here](https://github.com/elastic/go-elasticsearch/blob/7147ab205761e88e45f48ee5e1a2937bc820e9d7/_examples/xkcdsearch/store.go#L226)), we have the following query:

```
"query" : {
	"multi_match" : {
		"query" : %q,
		"fields" : ["title^100", "alt^10", "transcript"],
		"operator" : "and"
	}
},
```

What makes me nervous/unsure is the part _%q_. Do I need to sanitize _%q_ if I pass it with user-data? If so, what would be the correct way?

Is it possible that a user inserts malicious (causing elasticsearch to run OOM, dump the index, etc. etc.) queries into my search query?

**Comment by karmi** [comment]
There is no danger of "query injection" with the [`multi_match`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html) query, eg. it doesn't expand wildcards. Of course, user-provided input always needs to be treated carefully — I imagine it would be possible to send a malformed payload there.

Note that things are different with the `query_string` query, which can be quite easily used for stressing the cluster. Things get really dangerous if people could pass their own scripts, but that's not something possible out-of-the-box, unless you allow them to do it.

**Comment by moon-bits** [comment]
> Of course, user-provided input always needs to be treated carefully

See, that's the point. I'm reading this now on every forum, blog, etc. but no one is explaining how someone can prevent that in elasticsearch.
How would you expose a search API that takes some words as query parameter from a user?

> it would be possible to send a malformed payload there.

Could you elaborate on that more? How can I prevent that? Is there something for 'sanitation' within go-elasticsearch?

Thanks, karmi!

**Comment by karmi** [comment]
In general, taking in the input and sending it in the `multi_match` query is safe. I've mentioned a "malicious payload" because I can imagine somebody can come up with some sort of "unicode bomb" — unparseable content, monstrously big content, etc. Some lightweight sanitation like limiting the allowed length of the query (a regular query won't have 1,000,000 characters) or limiting the Unicode range (which is hard to do, though) might make sense. But a fulltext query is not susceptible to a regular SQL injection attack in the "little bobby tables" sense.

> How would you expose a search API that takes some words as query parameter from a user?

The example you've found is actually a pretty solid way of solving that: just feed it to a `match` or `multi_match` query. Using [`strconv.Quote()`](https://pkg.go.dev/strconv?tab=doc#Quote) might improve it a bit.

**Comment by moon-bits** [comment]
Great, I was looking for that confirmation!

Thank you very much!

**Comment by jmrah** [comment]
> But a fulltext query is not susceptible to a regular SQL injection attack in the "little bobby tables" sense.

For the uninitiated, [little bobby tables](https://xkcd.com/327/)
