### ISSUE TITLE
 Memory leak when losing connection with server

### ISSUE THREAD

**Issue by cuong58** [elastic/go-elasticsearch#159]
**Issue**

Our service serves 40-50 requests/sec. When it lost connection with the ES server for 15 minutes, the amount of memory occupied increases to more than 300MB. I have found out where the memory is leaking:
https://github.com/elastic/go-elasticsearch/blob/698f9f3b9fe3cac9c648569e095e5ad8d2c671c3/estransport/estransport.go#L258
When losing connection with the server, err == nil but res.StatusCode == 502 and res.Body contains error message data.
If max tries > 1, I think that res.Body.Close() should be called before the next retry.

**How to reproduce this bug**

1. Use Nginx to route all requests from http://0.0.0.0:9200 to http://0.0.0.0:9201 that is not available.
2. Create an es client to send 10.000 search requests to http://0.0.0.0:9200. 
3. Check memory occupied by the client process.

**Comment by karmi** [comment]
Hi, sorry for the delay here! So I understand that the error happens when a proxy in the middle returns an `502` error, is that right? If the client is retrying in this situation, `res.Body` should be closed (and drained) after the following code:

https://github.com/elastic/go-elasticsearch/blob/68f14edba6d35cbf14652c26f89f2e99b5e4cb6c/estransport/estransport.go#L307-L313

Is that right? I'll have a look into a reproduction and a fix.

**Comment by cuong58** [comment]
Thanks for your response!
You have understood exactly the problem that I encountered.

**Comment by karmi** [comment]
I've fixed the memory leak and merged the patch into `master` and `7.x` branches.

This was a little hard to reproduce for me, since the OS reported a stable value with tools such as `ps -axm -o %mem,rss,comm | grep 'go$'`, and I had to observe the memory growing by using the `runtime` Go package.

For the record, this is the full test script I've used:

```golang
//+build ignore

package main

import (
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math"
	"net/http"
	"os"
	"runtime"
	"strings"
	"time"

	_ "net/http/pprof"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/esapi"
	"github.com/elastic/go-elasticsearch/v8/estransport"
)

var (
	_ = fmt.Print
	_ = context.WithTimeout
	_ = math.Exp
	_ = strings.NewReader
	_ = http.DefaultClient
)

func main() {
	log.SetFlags(0)

	go func() { log.Fatalln(http.ListenAndServe("localhost:6060", nil)) }()

	count := 10000

	cfg := elasticsearch.Config{
		Addresses: []string{"http://localhost:8000"},
		Logger:    &estransport.ColorLogger{Output: os.Stdout},
		// RetryBackoff:  func(i int) time.Duration { return time.Duration(0) },
	}

	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}
	log.Println("Client ready with URLs:", es.Transport.(*estransport.Client).URLs())

	for i := 0; i < count; i++ {
		var (
			res *esapi.Response
			err error
		)

		res, err = es.Info()

		if err != nil {
			log.Printf("Error getting response: [%T]: %s", err, err)
		}

		io.Copy(ioutil.Discard, res.Body)
		res.Body.Close()

		if i%10 == 0 {
			printMemUsage()
		}
	}

	log.Println("Waiting...")
	time.Sleep(time.Hour)
}

func printMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	fmt.Printf("   m.Sys: %v MB\n", m.Sys/1024/1024)
}
```

This is the Nginx configuration used:

```
# docker run --name nginx --volume $PWD/nginx-proxy.conf:/etc/nginx/nginx.conf --publish 8000:8000 --network elasticsearch --rm nginx

user nginx;

worker_processes auto;
worker_rlimit_nofile 10240;
pid nginx.pid;

error_log off;

events {
  worker_connections  10240;
  accept_mutex        off;
  multi_accept        off;
}

http {
	upstream elasticsearch {
    server es1:9200;
  }

  server {
    listen 8000 default_server;

		location / {
      proxy_pass http://elasticsearch;
    }

    location /status {
      stub_status;
    }
  }
}

```
