### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by mihaiav** [elastic/go-elasticsearch#16]
Where can I find a Go client for ES?

**Comment by tsg** [comment]
Sorry for the radio silence on this. The development got stalled but we have concrete plans to reboot the development process on this in October. Still, it will be at least a few more months until the client will be in a usable state.

**Comment by andriisoldatenko** [comment]
@tsg please let me know if you need any help or contribution to this project?

**Comment by mpenate** [comment]
This is quite disappointing... would be nice to have some kind of response. Please, if you are not working on this mark as stale and we will find a way to go on.

**Comment by karmi** [comment]
Hello all, sorry for the long silence.

We have been working on the client since autumn last year, and tried to push publicly as soon as possible, but not sooner: we wanted to prevent unnecessary breaking changes for your code.

The day has finally come: a new set of packages has been just pushed to the `master` branch — feedback is welcome here in Github issues!
