### ISSUE TITLE
[BUG] BulkIndexerItem body io.Reader used before OnFailure is called

### ISSUE THREAD

**Issue by l1redd** [elastic/go-elasticsearch#161]
It is impossible to read from the `item.Body` `io.Reader` that is in the function signature of `OnFailure` in the `BulkIndexerItem` because it has already been read from in the `esutil/bulk_indexer.go` code. 

The item.Body io.Reader is read from here:
https://github.com/elastic/go-elasticsearch/blob/68f14edba6d35cbf14652c26f89f2e99b5e4cb6c/esutil/bulk_indexer.go#L415

Then this same item is used as an argument in the OnFailure function:
https://github.com/elastic/go-elasticsearch/blob/68f14edba6d35cbf14652c26f89f2e99b5e4cb6c/esutil/bulk_indexer.go#L524

So when I try to access it in the OnFailure function, it returns an empty string. For example:
```go
err = bi.Add(
	ctx,
	esutil.BulkIndexerItem{
		Action:     "index",
		Body:       bytes.NewReader(someBytes),
		DocumentID: "1",
		OnFailure: func(ctx context.Context, item esutil.BulkIndexerItem, res esutil.BulkIndexerResponseItem, err error) {

			if err != nil {
				log.Printf("error")
			} else {
				log.Printf("error in response body")
			}
			// **** Reading from item.Body returns an empty string***
			bodyBytes, err := ioutil.ReadAll(item.Body)
                        bodyString := string(bodyBytes) // bodyString is ""
                        log.Printf("Body: %s", bodyString)
		},
	},
)
```

Can I get some help on fixing this bug. I think the body needs to be saved when it's read, and then the item's body io.Reader  just needs to be reinstantiated with that body before being used as an argument in OnFailure. Happy to submit a bug fix PR if that would be faster. Thanks!

**Comment by l1redd** [comment]
@karmi

**Comment by karmi** [comment]
You're right, the item body is consumed when it's serialized and sent over the wire. To access it from the callback, it needs to be duplicated and reinstated indeed, in a similar manner to what happens in https://github.com/elastic/go-elasticsearch/blob/68f14edba6d35cbf14652c26f89f2e99b5e4cb6c/estransport/estransport.go#L248 or https://github.com/elastic/go-elasticsearch/blob/68f14edba6d35cbf14652c26f89f2e99b5e4cb6c/estransport/estransport.go#L264

The implementation here needs to be careful to _not_ duplicate the body when the callbacks are not defined, in order to not allocate more than is needed. I'd be happy to assist with a PR, and I can also look into it myself, after I clean up some other things going on right now.

**Comment by l1redd** [comment]
Thanks for the quick response! I'm going to dig into this and hopefully put up a PR for you to review in the next few days.

**Comment by mbudge** [comment]
I think this is affecting the on success callback too.
