### ISSUE TITLE
Standard way to get request string

### ISSUE THREAD

**Issue by rbcervilla** [elastic/go-elasticsearch#23]
I see that there is a method to get Response as string. However there is not to get request as string. Sometines it's useful for debugging.
The only way I can do it is creating a custom transport, like this:

```go
package main

import (
	"context"
	"log"
	"net/http"
	"net/http/httputil"
	"strings"

	"github.com/elastic/go-elasticsearch"
	"github.com/elastic/go-elasticsearch/esapi"
)

type LogRequest string

type LoggerTransport struct {
	transport http.RoundTripper
}

func (t *LoggerTransport) RoundTrip(req *http.Request) (*http.Response, error) {

	lr := req.Context().Value(LogRequest("log"))
	if lr != nil && lr.(bool) == true {
		requestDump, err := httputil.DumpRequest(req, true)
		if err == nil {
			log.Printf("Request: %s", string(requestDump))
		}
	}

	return t.transport.RoundTrip(req)
}

func main() {

	log.SetFlags(0)

	es, err := elasticsearch.NewClient(elasticsearch.Config{Transport: &LoggerTransport{transport: http.DefaultTransport}})
	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}
	
	req := esapi.IndexRequest{
		Index:      "test",
		DocumentID: "1",
		Body:       strings.NewReader(`{"title" : "` + "Test title" + `"}`),
		Refresh:    "true",
	}
	
	res, err := req.Do(context.WithValue(context.Background(), LogRequest("log"), true), es)
	if err != nil {
		log.Fatalf("Error indexing document: %s", err)
	}

	log.Printf("Response: %s", res.String())
}
```

Through a WithParam context selectively I log or not.
It would be possible to have another way to do this?

Thanks.

**Comment by karmi** [comment]
Hi, you're right: the ability to inspect the request is crucial for debugging. Note that among the included examples, there's one for logging, specifically:

https://github.com/elastic/go-elasticsearch/blob/144b86dc76daa2440f49cc3041fa46a2002ac73c/_examples/customization.go#L20

Among the planned features for the client is an automatic logging of request/responses, aligned with the clients in other languages — see eg. the [Ruby client](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#logging).

This will be a little trickier in Go, since it doesn't present any standard interface for logging, and there are many logging packages, ranging from the standard library's `log` to structured loggers like `uber-go/zap` or `rs/zerolog`. I'm currently investigating the ideas, ranging from simply exposing a `Logger` field taking an `io.Writer`, to exposing a function to allow customizing the log output.

In your case, though, it looks like there's a simpler solution: adding a `String()` method to the `esapi.Request` type, which you would then use similarly as the `res.String()` in your example above.

I like this idea, since it would make the request and response types symmetric, and would provide an easy way to print out the request for debugging.

**Comment by rbcervilla** [comment]
Hi, thank you. I didn't see the customization example, I'm sorry.

I think it would be nice to add a `String()` method for all `esapi.Request` types, matching `stringer` interface of fmt package. But some request information isn't in the 
`esapi.Request` types. Method and path is set on `Do(...)` method. Example:
https://github.com/elastic/go-elasticsearch/blob/144b86dc76daa2440f49cc3041fa46a2002ac73c/esapi/api.index.go#L68-L86

Should the `String()` method return this info, right?

**Comment by karmi** [comment]
Yes, you're correct — this would have to be extracted to a different method, and called both from `Do()` and `String()`. I was considering that approach during development, ie. having a method like `prepare()`, `toRequest()`, etc — but ultimately decided against it, to keep the code flow more simple to follow.

After some consideration, while making the request structs a `fmt.Stringer` _is_ attractive, the benefits are not as high as the costs: for one, you wouldn't be able to use it when you call the API _methods_ (`Index("test", ...)`) and not construct the struct manually.

Hence, I think that providing the bundled logging support I've mentioned above yields more benefits. I have some ideas how to make logging both "automatic" for simple debugging and powerful enough for production use (custom loggers, etc). I'll try to open a PR soon and reference this issue.

**Comment by rbcervilla** [comment]
> After some consideration, while making the request structs a `fmt.Stringer` _is_ attractive, the benefits are not as high as the costs: for one, you wouldn't be able to use it when you call the API _methods_ (`Index("test", ...)`) and not construct the struct manually.

You're right, I noticed it after reply. As you mentioned, it may better to include a suitable logging support. 
Thank you!

**Comment by karmi** [comment]
Hello, I've pushed the initial implementation of the logging support to https://github.com/elastic/go-elasticsearch/pull/39.

**Comment by karmi** [comment]
I've added the implementation of the `estransport.Logger` interface and also two comrehensive examples for using the default or custom loggers to https://github.com/elastic/go-elasticsearch/tree/master/_examples/logging. Please have a look!
