### ISSUE TITLE
No docker container for 7.x

### ISSUE THREAD

**Issue by mikepc** [elastic/go-elasticsearch#38]
I know the client targets 7.x of elasticsearch, but there aren't even any official docker images for elasticsearch 7.x

Kind of a big miss not to support ES 6 before ES7 is even readily available.

**Comment by karmi** [comment]
Hello, a `7.0.0-beta1` image is available at https://www.docker.elastic.co/#elasticsearch-7-0-0-beta1, so that shouldn't be a problem?

Furthermore, "snapshot" images are also available, though not listed on the docker.elastic.co site, the client uses them for integration tests, see eg.:

https://github.com/elastic/go-elasticsearch/blob/60ea51fd3784506e6f2e45444a1e024c2fd8aff0/Makefile#L131

Note also that I've already added support for the [`6.x`](https://github.com/elastic/go-elasticsearch/tree/6.x) and even [`5.x`](https://github.com/elastic/go-elasticsearch/tree/5.x) versions, and continue working on a proper release tooling for these versions, along proper compatibility table in the documentation.

**Comment by karmi** [comment]
Hi @mikepc , can I help further with this issue?
