### ISSUE TITLE
I'm getting an interesting error

### ISSUE THREAD

**Issue by delgec** [elastic/go-elasticsearch#403]
Hello everyone

When I run the below query in the Dev Tools, it's worked correct but go-elasticsearch package it's returning wrong data

I'm filtering by language field and the language value is tr-TR but it's returning tr-TR and tr-CY (both) 

How can I fix it?

Thanks

query := `{"query":{"bool":{"must":[{"match":{"language":"tr-TR"}}]}}}`

      res, err := s.client.Search(
		s.client.Search.WithContext(ctx),
		s.client.Search.WithIndex("my_index"),
		s.client.Search.WithBody(strings.NewReader(query)),
		s.client.Search.WithFrom(from),
		s.client.Search.WithSize(size),
		s.client.Search.WithSort("published_at:desc"),
	)

**Comment by Anaethelion** [comment]
Hi @delgec could you provide an example of your data and the parameters you are passing to the options in your search query ?

To debug what is sent you can inject a logger in the client configuration like this:
```go
cfg := elasticsearch.Config{
		Logger: &elastictransport.ColorLogger{Output: os.Stdout},
}
elasticsearch.NewClient(cfg)
```

It would print the request and response to the standard output and will help you understand what's going on.

**Comment by delgec** [comment]
> Hi @delgec could you provide an example of your data and the parameters you are passing to the options in your search query ?
> 
> To debug what is sent you can inject a logger in the client configuration like this:
> 
> ```go
> cfg := elasticsearch.Config{
> 		Logger: &elastictransport.ColorLogger{Output: os.Stdout},
> }
> elasticsearch.NewClient(cfg)
> ```
> 
> It would print the request and response to the standard output and will help you understand what's going on.


Thanks for your reply.

I created a repository and uploaded my code. 

Could you check the code pls?

https://github.com/delgec/go-elasticsearch-sample

**Comment by Anaethelion** [comment]
I've taken a quick look and nothing seems wrong with the client.
The match query you run with the standard analyzer probably searches for "tr" and "TR" which returns more hits than you want. I'd advise to change for a `match_phrase` instead of a `match` and make sure you index this field as a `keyword`.

If you need further help with the Elasticsearch API, I'd advise you to post on the [Elastic Discuss Forum](https://discuss.elastic.co/).

I do need to point out that the repository you linked is public and contains valid credentials to a running cloud instance. You should remove those as soon as possible as someone with malicious intent could exploit your account.
