### ISSUE TITLE
Why does elasticsearch.genuineCheckHeader throw an error?

### ISSUE THREAD

**Issue by Vortelf** [elastic/go-elasticsearch#515]
I'm currently developing an app and the app happens to use OpenSearch instead of Elastic.
This client works without any issues with the OpenSearch instance, but methods like `Info()` and `Ping()` throw an error because of the missing `X-Elastic-Product` header.

My question here why is there such approach? Why is there a need to do the whole `doProductCheck` and prevent the usage of the whole library as after a failed check, it returns `nil` instead of the successful response from the OpenSearch?

My proposal is for the method to only print an error message.

```go
func genuineCheckHeader(header http.Header) error {
	if header.Get("X-Elastic-Product") != "Elasticsearch" {
		fmt.Errorf(unknownProduct)
	}
	return nil
}
```

Ideally, it would be best if this check if gone for good as the library obviously works with other implementations different from Elastic's. And people won't have to make forks just to obfuscate such shenanigans.

**Comment by sethmlarson** [comment]
The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.

You can see [this thread](https://github.com/elastic/elasticsearch-py/issues/1676#issuecomment-896291596) for additional reasons we've had to implement such a change to our clients.

**Comment by Vortelf** [comment]
@sethmlarson Here's another question then - why not collaborate with AWS to create a unified library since their OpenSearch is a fork and most of the functionalities overlap?

Then again - you've added a message to inform the users that the library is not compatible with other products, this should be a well enough indicator to the users in order to not spam issues. Why is the whole functionality disabled? It's a library - it's used by developers. They know well enough that if it's compatibility issue and they have an error message, it's them who caused the problem, which as stated is problem with missing APIs in OpenSearch. But simple functionalities like Index work regardless of the platform.

And criticism on the shameless plug - it's not up to me to decide what we use in the corporation. It's up to you to sell it to us.
