### ISSUE TITLE
Unable to Use Wildcard When Targeting Data Streams with UpdateByQuery

### ISSUE THREAD

**Issue by weslambert** [elastic/go-elasticsearch#529]
When using `UpdateByQuery`, I am unable to target a data stream using a wildcard. 

For example:

```
 indexPatterns := []string{'mydatastreamprefix-*'}
 res, err := client.UpdateByQuery(
	        indexPatterns,
		client.UpdateByQuery.WithContext(ctx),
		client.UpdateByQuery.WithPretty(),
		client.UpdateByQuery.WithConflicts("proceed"),
		client.UpdateByQuery.WithBody(read),
		client.UpdateByQuery.WithRefresh(true),
		client.UpdateByQuery.WithWaitForCompletion(true),
 )
```

However, this works fine if I target an _index_ with a wildcard. Is this functionality missing from the client?

Thanks!
Wes

**Comment by Anaethelion** [comment]
Hi @weslambert the client doesn't know the difference between an index and a datastream. If one works so should the other.

If you follow the documentation on how to [set up a datastream](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-a-data-stream.html), you'll see that the index pattern named `my-data-stream*` then leads to creating a datastream with the name `my-data-stream` which is what should be used when referring to this specific datastream.

By the look of your code, it seems you are trying to target the index pattern of the index template rather than the datastream's name.
You can check for your datastream names using a `GET /_data_stream` of course.

Am I missing something ? If so, please let me know!

**Comment by weslambert** [comment]
Right, I (think) am aware of how data streams work. 

The nomenclature in the code is poorly worded.

As I mentioned, I cannot target a group of data streams using a pattern, such as:

`logs-blah1`
`logs-blah-2`

...with something like `logs-*`

**Comment by Anaethelion** [comment]
All clear, what you want is expansion of the datastream name.
Like `/my-data-stream-*/_update_by_query` would translate to `/my-data-stream-1,my-data-stream-2/_update_by_query` automatically.

I've managed to replicate your issue within my test setup directly in Kibana, I'm going to dig further and will update this issue accordingly.

In the meantime could you provide the version of the Elasticsearch cluster you are running on ?

**Comment by weslambert** [comment]
Correct, thank you! This was tested using version `8.3.x`.

**Comment by weslambert** [comment]
Hi @Anaethelion, I just wanted to follow up an see if you were able to find out anything else around this issue.

Thanks!
Wes

**Comment by Anaethelion** [comment]
Hi @weslambert 

Sorry for the late reply, I took extra time to check and this limitation isn't on client side.

I've created https://github.com/elastic/elasticsearch/issues/90272 to track this issue.

Closing this one.

**Comment by weslambert** [comment]
Great, thank you!
