### ISSUE TITLE
bulkProcessor  add panic send on closed channel

### ISSUE THREAD

**Issue by csz062211** [elastic/go-elasticsearch#533]
When using the bulkProcessor add function, under what circumstances will panic 
panic is send on closed channel What is the best posture to use bulkProcessor

**Comment by Anaethelion** [comment]
`bulkProcessor` is a class of the Java Transport Client, are you sure this is the right repository ? If not documentation for the `bulkProcessor` [can be found here](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html).

Otherwise, if you are trying to find some examples for the `BulkIndexer` of the Go client, here is a simple [code example](https://github.com/elastic/go-elasticsearch/blob/main/esutil/bulk_indexer_example_test.go) and an [example project](https://github.com/elastic/go-elasticsearch/tree/main/_examples/bulk) which goes a bit deeper.
