### ISSUE TITLE
es.Update support id []string?

### ISSUE THREAD

**Issue by Capricornwqh** [elastic/go-elasticsearch#547]
type Update func(index string, id string, body io.Reader, o ...func(*UpdateRequest)) (*Response, error)
this func only updates a document with a script. how to updates multiple document ids?

command line is work:
curl --cacert http_ca.crt -u elastic -XPOST https://localhost:9200/test/_update/{VK3fK4QBlRhZOy7i807,Uq3fK4QBlRhZOy7isU6v}?pretty

**Comment by sethmlarson** [comment]
Thanks for opening this issue. Since the Elasticsearch update API only is meant to target a single document at a time we likely won't add support for that natively in the client. Instead you can either call the bulk API with your updates or call the update API multiple times with the different document IDs. Hope that helps!
