### ISSUE TITLE
Error when using the client：net/http: HTTP/1.x transport connection broken: malformed HTTP status code "is"

### ISSUE THREAD

**Issue by chen-mou** [elastic/go-elasticsearch#633]
it my configure
![image](https://user-images.githubusercontent.com/42209673/228195296-4878bd65-b56d-48f8-97b0-3506ac29bf6b.png)
code
![image](https://user-images.githubusercontent.com/42209673/228195412-f5c2800d-477c-4a15-ae5b-0620b92eb935.png)
result
![image](https://user-images.githubusercontent.com/42209673/228195451-d1476e8a-ceae-4ff8-88b4-75eecc020343.png)
why is this happening and what should i do

**Comment by rlch** [comment]
Facing the same issue using the default transport with TLS in K8s. Here's my configuration, and I'm using the typed client:
`go
	var caCert []byte
	address := c.Host
	var transport *http.Transport
	if c.Port != "" {
		address = address + ":" + c.Port
	}
	if c.CertsDir != "" {
		var err error
		caCert, err = os.ReadFile(path.Join(c.CertsDir, "ca.crt"))
		if err != nil {
			return nil, err
		}
		certPool := x509.NewCertPool()
		var (
			cert = path.Join(c.CertsDir, "tls.crt")
			key  = path.Join(c.CertsDir, "tls.key")
		)
		if ok := certPool.AppendCertsFromPEM(caCert); !ok {
			return nil, errors.New("failed to append ca cert")
		}
		certPair, err := tls.LoadX509KeyPair(cert, key)
		if err != nil {
			return nil, err
		}
		transport = http.DefaultTransport.(*http.Transport).Clone()
		transport.TLSClientConfig = &tls.Config{
			RootCAs:            certPool,
			Certificates:       []tls.Certificate{certPair},
			InsecureSkipVerify: true,
		}
	}
	return &elasticsearch.Config{
		Addresses: []string{address},
		Username:  c.User,
		Password:  c.Password,
		CACert:    caCert,
		Transport: transport,
	}, nil
`

@chen-mou Let me know if you figure this out -- I suspect this could be due to misconfiguration. I can run ES fine in Docker but not K8s.

**Comment by Anaethelion** [comment]
@chen-mou The error you are receiving is because you are targeting the `9300` port of Elasticsearch which is used for inter-nodes communication.
The Go client is a REST client which should be used with the `9200` port exposed by the server.

@rlch Let  me know if you face the same issue, feel free to open a new issue if that's not the case!
