### ISSUE TITLE
[TypedClient] Upgrade from 8.7.0 -> 8.7.1. Indices Exists Do() method missing.

### ISSUE THREAD

**Issue by practical-coder** [elastic/go-elasticsearch#667]
Hello, I am moving project codebase from `olivere/elastic` driver (on Elasticsearch 7.x) 
to `go-elasticsearch` typedapi (on Elasticsearch 8.7).
After upgrading `go-elasticsearch` to 8.7.1 compilation fails on:
`tc/index.go:61:3: TC.Indices.Exists(idx.Name).Do undefined (type *"github.com/elastic/go-elasticsearch/v8/typedapi/indices/exists".Exists has no field or method Do)`

Here is relevant file (8.7.1) without `Do` method:
https://github.com/elastic/go-elasticsearch/blob/v8.7.1/typedapi/indices/exists/exists.go
and one with `Do` method (8.7.0):
https://github.com/elastic/go-elasticsearch/blob/v8.7.0/typedapi/indices/exists/exists.go#L153

**Comment by Anaethelion** [comment]
Hi @practical-coder,

The presence of the `Do` method in `8.7.0` was a bug, it didn't return anything since this endpoint doesn't provide its answer within the body but rather in the status code.

Rather you should use `IsSuccess` which will give you a true `bool` in case of success, or you could use `Perform` and retrieve the `HttpResponse` directly.

**Comment by practical-coder** [comment]
Ok, thank you for clarification @Anaethelion !
I've started using typedapi since `8.7.0` and used `Do` method in other indices management endpoints,
so I've done it in similar way using Exists endpoint.
