### ISSUE TITLE
`BucketsPathBuilder` Should Accept `string` and `[]string` Inputs, Not Just `map[string]string`

### ISSUE THREAD

**Issue by FrancoisChastel** [elastic/go-elasticsearch#675]
Hello, I'm currently using the `go-elasticsearch` library (version 8) and encountered a limitation with the `BucketsPathBuilder` method.

When using aggregations, the BucketsPathBuilder method currently only accepts a map[string]string. Here is a code snippet to illustrate:

```go

aggregations := map[string]*types.AggregationContainerBuilder{
		"trend": types.NewAggregationContainerBuilder().SerialDiff(
			types.NewSerialDifferencingAggregationBuilder().BucketsPath(types.NewBucketsPathBuilder().BucketsPath(map[string]string{"average": "average"})).
				GapPolicy(gappolicy.Insertzeros).Lag(
				int(2),
			),
		),
		"average": types.NewAggregationContainerBuilder().Avg(
			types.NewAverageAggregationBuilder().Field(types.Field("my_field")),
		),
	}
```

However, for my use case, it would be significantly more useful if the BucketsPathBuilder could accept not only map[string]string but also string and []string inputs. The current implementation is restrictive and does not correctly support all possible use cases.

I would greatly appreciate it if the library could be enhanced to support this feature. Thank you in advance for considering this request.

**Comment by Anaethelion** [comment]
Hi @FrancoisChastel 

Thank you for the feedback, this version is not supported anymore and the builder pattern has since been removed from the alpha period.

Furthermore in the most recent version you will see that the `SerialDifferencingAggregation` now accepts an interface for the `BucketsPath` which allows you to set either a map or an array as arguments.

I would advise you to upgrade to the latest version which will also allow you to have typed responses!

**Comment by FrancoisChastel** [comment]
Fantastic ! Thank you :)
