### ISSUE TITLE
[QUESTION] Use v6 or v7 with minimum code 

### ISSUE THREAD

**Issue by MarcMagnin** [elastic/go-elasticsearch#96]
Hey,

How can we use the v6 OR v7 depending on what elastic is setup with the least amout of code to switch between clients.
I've tried with something such as 
```
func (e *ElasticsearchConnector) getClient() interface{} {
	if e.es7Client != nil {
		return e.es7Client
	}
	return e.es6Client
}
```
but it'll not work because they aren't in the same package.

**Comment by karmi** [comment]
Hey! This type of dynamic / polymorphic behaviour is perhaps quite hard to achieve in Go. Since the `getClient()` method returns an empty `interface{}`, you'd have to type-switch in the calling code, somehow like `client.(*elasticsearch7.Client).Info()`.

While the package versioning does allow using multiple versions in one project, the main use case for those is having two separate clients, declared eg. in `es6` and `es7`, and calling them separately, such as `es6.Info()` and `es7.Info()`.

Maybe there are some more tricks to do, I'll think about it some more. But I'm afraid that the strict type system would prevent it.

**Comment by MarcMagnin** [comment]
To prevent using switch cases, I haven't found any better way than embedding the clients in structs that inherit an interface with the things that I'll use. As an example, getting the version of elastic:

```
type GenericElasticClient interface {
	Version() (string, error)
}
type ES6 struct {
	Client *elasticsearch6.Client
}
type ES7 struct {
	Client *elasticsearch7.Client
}
func (c *ES6) Version() (string, error) {
	res, err := c.Client.Info()
	if err != nil {
		return "", err
	}
	defer res.Body.Close()
	defer io.Copy(ioutil.Discard, res.Body)
	if res.IsError() {
		return "", fmt.Errorf(res.String())
	}
	var r map[string]interface{}
	if err := json.NewDecoder(res.Body).Decode(&r); err != nil {
		return "", fmt.Errorf("error parsing the response body: %s", err)
	}
	return fmt.Sprintf("%s", r["version"].(map[string]interface{})["number"]), nil
}
func (c *ES7) Version() (string, error) {
    // ... ES7 code related
}
```

Then wrap a generic client like this:
```
someObject.esClient = &ES6{
		Client: e.es6Client,
	}
// or 
someObject.esClient = &ES7{
		Client: e.es7Client,
	}

ver, err := someObject.esClient.Version()

```

**Comment by karmi** [comment]
Yeah, that works, and with a bit of code generation, would perhaps even be feasible...

**Comment by MarcMagnin** [comment]
closing, but feel free to add other ideas ;)
